version: '4.0'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: reserve
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  springboot-app:
    build: ./
    container_name: springboot-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/reserve
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.yaml
    ports:
      - "8084:8084"
    networks:
      - app-network
    volumes:
      - ./db/changelog:/app/db/changelog
      - ./logs:/app/logs
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
